version: "3"
services:
  # OPA Server
  opa:
    build: ./apps/opa
    ports:
      - "8181:8181"
  # Proxy
  s3-guard:
    build: ./apps/proxy
    ports:
      - "4000:4000"
    env_file: .env.local
